name: CD

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ CI ]
    types: [ completed ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  JAVA_VERSION: '21'
  JAVA_DISTRIBUTION: 'temurin'

jobs:

  cancel-on-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: [ ubuntu-latest ]
    name: 'No CD when CI failed'
    steps:
      - run: echo 'CI failed - CD does not run'

  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    name: 'Package & Upload Installers'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: 'maven'

      - name: Install Application Packages
        run: ./mvnw package install

      - name: Create Ubuntu installer
        if: ${{ matrix.os == 'ubuntu-latest' }}
        shell: bash
        run: bash .github/scripts/create-installer-linux.sh
      - name: Create Mac OSX installer
        if: ${{ matrix.os == 'macos-latest' }}
        shell: bash
        run: bash .github/scripts/create-installer-macosx.sh
      - name: Create Windows installer
        if: ${{ matrix.os == 'windows-latest' }}
        shell: cmd
        run: .github/scripts/create-installer-windows.bat

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MowItNow-${{ matrix.os }}
          path: 'target/installer/MowItNow*'
          retention-days: 7
